spring:
  profiles:
    include:
    - secrets
  jpa:
    show-sql: true
  application:
    name: fupboard-api
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
fupboard:
  oauth2:
    token-uri: https://www.googleapis.com/oauth2/v3/token
