name: "Terraform"

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: "Manage aws resources"
    runs-on: ubuntu-22.04
    outputs:
      dbhost: ${{ steps.tf_outputs.outputs.dbhost }}
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_db_password: ${{ secrets.TF_VAR_DB_PASSWORD }}
      TF_VAR_db_username: ${{ secrets.TF_VAR_DB_USERNAME }}
      TF_VAR_key_name: privatekey.pem
    defaults:
      run:
        working-directory: terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.0.1
          terraform_wrapper: false

      - name: Terraform Init
        id: init
        run: terraform init -backend-config="bucket=${{ secrets.AWS_BUCKET_NAME }}" -backend-config="key=${{ secrets.AWS_BUCKET_KEY }}" -backend-config="region=af-south-1"

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Capture Terraform Outputs
        id: tf_outputs
        run: |
          echo "dbhost=$(terraform output -raw db_host)" >> $GITHUB_OUTPUT

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '23'

      - name: Setup Maven
        run: |
          sudo apt update
          sudo apt install maven

      - name: Create Secrets File
        working-directory: ./fupboard-api/src/main/resources
        run: |
          file=application-secrets.yml
          echo "spring:" > $file
          echo "  datasource:" >> $file
          echo "    url: jdbc:postgresql://$DB_HOST/fupboarddb" >> $file
          echo "    username: $TF_VAR_db_username" >> $file
          echo "    password: $TF_VAR_db_password" >> $file
          echo "  security:" >> $file
          echo "    oauth2:" >> $file
          echo "      resourceserver:" >> $file
          echo "        jwt:" >> $file
          echo "          audiences:" >> $file
          echo "          - ${{ secrets.CLIENT_ID }}" >> $file
          echo "fupboard:" >> $file
          echo "  oauth2:" >> $file
          echo "    client-id: ${{ secrets.CLIENT_ID }}" >> $file
          echo "    client-secret: ${{ secrets.CLIENT_SECRET }}" >> $file

      - name: Build JAR with Maven
        working-directory: ./fupboard-api
        run: |
          mvn clean install
          
      - name: Deploy to EC2
        working-directory: ./fupboard-api/target
        run: |
          EC2_HOST=$(terraform output -raw ec2_host)
          echo "ec2_host=$EC2_HOST"
          scp -i ../../privatekey.pem fupboard-api-0.0.1-SNAPSHOT.jar $EC2_HOST:fupboard-api.jar
          ssh -i ../../privatekey.pem $EC2_HOST "systemctl restart fupboard.service"
  flyway:
    needs: terraform
    name: Flyway migrations
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run Flyway Migrations
        run: |
          docker run --rm --volume ${{ github.workspace }}/migrations:/flyway/sql:ro redgate/flyway -url="jdbc:postgresql://${{ needs.terraform.outputs.dbhost }}/fupboarddb" -user="${{ secrets.TF_VAR_DB_USERNAME }}" -password="${{ secrets.TF_VAR_DB_PASSWORD }}" migrate